name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 16,22,4,10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: SYuan03
          BRANCH_NAME: main
          UTC_OFFSET: 8
          AUTO_PUSH: true
